name: FriendsX
version: 2.0.1
main: Akari_my\FriendsX\Main
api: 5.0.0
author: Akari_my
description: Advanced friend system

permissions:
  friendsx.command:
    default: true
  friendsx.migrate:
    description: Allows running data migration
    default: op